version: '2.4'

services:
  traefik:
    command:
      - --api.dashboard=true
      - --api=true
      - --entrypoints.http.address=:80
      - --log.level=INFO
      - --providers.docker.exposedbydefault=false
      - --providers.docker=true
    env_file: .env
    image: traefik:v2.4.3
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_SUBDOMAIN-traefik}.${TRAEFIK_DOMAIN-localhost}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.port=8080
    ports:
    - ${TRAEFIK_HOST_PORT_HTTP-8080}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portainer:
    image: portainer/portainer-ce:2.1.1-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_SUBDOMAIN-portainer}.${PORTAINER_DOMAIN-localhost}`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    restart: always
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: traefik

volumes:
  portainer: