version: '2.4'

networks:
  default:
    internal: true
  public:
    external:
      name: ${COMPOSE_PROJECT_NAME}_public

services:
  statping:
    depends_on:
      - postgres
    env_file:
      - .env
      - ../../etc/${ENVIRONMENT-localhost}/.env
    image: statping/statping:v0.90.74
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_public
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-statping.entrypoints=http
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-statping.rule=${STATPING_TRAEFIK_RULE}
    networks:
      - default
      - public
    restart: always
    volumes:
      - ../../var/statping/statping:/app
      - ../../etc/${ENVIRONMENT-localhost}/statping.yml:/app/services.yml

  postgres:
    environment:
      POSTGRES_PASSWORD: statping
      POSTGRES_USER: statping
      POSTGRES_DB: statping
    image: postgres:13.2
    networks:
      - default
    restart: always
    volumes:
      - ../../var/statping/postgres:/var/lib/postgresql/data
