version: '2.4'

networks:
  default:
    internal: true
  traefik:
    external:
      name: netconstructions-incongruesproxy_traefik

services:
  portainer:
    env_file: .env
    image: portainer/portainer-ce:2.1.1-alpine
    labels:
      - traefik.docker.network=netconstructions-incongruesproxy_traefik
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${SUBDOMAIN-portainer}.entrypoints=http
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${SUBDOMAIN-portainer}.rule=Host(`${SUBDOMAIN-portainer}.${DOMAIN-localhost}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-${SUBDOMAIN-portainer}.loadbalancer.server.port=9000
    networks:
      - default
      - traefik
    restart: always
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer: