version: '2.4'

networks:
  default:
    internal: true
  public:
    external:
      name: ${COMPOSE_PROJECT_NAME}_public

services:
  statping:
    depends_on:
      - postgres
    environment:
      DB_CONN: postgres
      DB_DATABASE: statping
      DB_HOST: postgres
      DB_PASS: statping
      DB_USER: statping
      DESCRIPTION: État des services hébergés par Pastis Hosting
      NAME: status.pastis-hosting.net
      VIRTUAL_HOST: ${COMPONENT}.${DOMAIN}
    image: statping/statping:v0.90.74
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_public
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${COMPONENT-status}.entrypoints=http
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${COMPONENT-status}.rule=Host(`${COMPONENT-status}.${DOMAIN-localhost}`)
    networks:
      - default
      - public
    restart: always
    volumes:
      - statping:/app

  postgres:
    image: postgres:13.2
    restart: always
    networks:
      - default
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: statping
      POSTGRES_USER: statping
      POSTGRES_DB: statping

volumes:
  postgres:
  statping: