version: '2.4'

networks:
  default:
    internal: true
  public:
    external:
      name: ${COMPOSE_PROJECT_NAME}_public

services:
  statping:
    depends_on:
      - postgres
    environment:
      DB_CONN: postgres
      DB_DATABASE: statping
      DB_HOST: postgres
      DB_PASS: statping
      DB_USER: statping
      DESCRIPTION: ${STATPING_DESCRIPTION}
      DISABLE_COLORS: "true"
      LANGUAGE: ${STATPING_LANGUAGE}
      NAME: ${STATPING_NAME}
      SAMPLE_DATA: "false"
      VIRTUAL_HOST: ${COMPONENT}.${DOMAIN}
    image: statping/statping:v0.90.74
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_public
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${COMPONENT}.entrypoints=http
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-${COMPONENT}.rule=Host(`${COMPONENT}.${DOMAIN}`)
    networks:
      - default
      - public
    restart: always
    volumes:
      - ./services.yml:/app/services.yml
      - statping:/app

  postgres:
    environment:
      POSTGRES_PASSWORD: statping
      POSTGRES_USER: statping
      POSTGRES_DB: statping
    image: postgres:13.2
    networks:
      - default
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  statping: