x-tcpservice: &tcpservice
  allow_notifications: true
  check_interval: 60
  notify_after: 0
  notify_all_changes: true
  public: true
  redirect: true
  timeout: 15
  type: tcp

x-httpsservice: &httpsservice
  allow_notifications: true
  check_interval: 45
  expected_status: 200
  method: GET
  notify_after: 2
  notify_all_changes: true
  port: 443
  public: true
  redirect: true
  timeout: 10
  type: http
  verify_ssl: true

x-httpservice: &httpservice
  port: 80
  verify_ssl: false
  <<: *httpsservice

services:

  # pastis-hosting.net

  ## endpoints
  - name: traefik.pastis-hosting.net
    domain: https://traefik.pastis-hosting.net
    permalink: traefik.pastis-hosting.net
    <<: *httpsservice

  - name: mirror.pastis-hosting.net
    domain: https://mirror.pastis-hosting.net
    permalink: mirror.pastis-hosting.net
    <<: *httpsservice

  - name: rebecca.pastis-hosting.net
    domain: https://rebecca.pastis-hosting.net
    permalink: rebecca.pastis-hosting.net
    <<: *httpsservice

  - name: status.pastis-hosting.net
    domain: https://status.pastis-hosting.net
    permalink: status.pastis-hosting.net
    <<: *httpsservice

  - name: www.jean-cloude.club
    domain: https://www.jean-cloude.club
    permalink: www
    <<: *httpsservice

  ## services
  - name: postgres
    domain: db
    port: 5432
    <<: *tcpservice
