version: '2.4'

networks:
  default:
    internal: true
  public:
    external:
      name: ${COMPOSE_PROJECT_NAME}_public

services:
  portainer:
    env_file:
      - .env
      - ../../etc/${ENVIRONMENT-localhost}/.env
    image: portainer/portainer-ce:2.1.1-alpine
    labels:
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_public
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-portainer.entrypoints=http
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-portainer.rule=${PORTAINER_TRAEFIK_RULE}
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-portainer.loadbalancer.server.port=9000
    networks:
      - default
      - public
    restart: always
    volumes:
      - ../../var/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
